### ISSUE TITLE
Update LICENSE to contain the copyright owner and the year

### ISSUE THREAD

**Issue by elinesterov** [sigstore/sigstore#1061]
**Description**

The license file doesn't have the copyright owner and year inside all sigstore repositories. It just contains the default template string from Github that needs to be updated:
`   Copyright [yyyy] [name of copyright owner]`

**Version**

Every single repo here.

Why is it a problem?
Anybody who is using any sigstore code in their products is supposed to mention License and copyright notice. Copyright Notice is supposed to mention the owner and year.

**Comment by cpanato** [comment]
That license is correct and very similar (not to say equal) to other open source projects, for example, Kubernetes (https://github.com/kubernetes/kubernetes/blob/master/LICENSE)

That specific part of the license is an appendix and explains how should use the license header in each file (https://github.com/sigstore/sigstore/blob/main/LICENSE#L179), and you can check, for example, how that is implemented in one file https://github.com/sigstore/sigstore/blob/main/pkg/cryptoutils/certificate.go#L1-L14

So that part of the license is just a template for the other files.

I hope that clarifies that.
thanks for the opening the issue
