### ISSUE TITLE
Use ed25519 for KMS's that support it? E.g. Vault

### ISSUE THREAD

**Issue by ropnop** [sigstore/sigstore#122]
**Description**

I know work was done to move from ed25519 to ecdsa in cosign [here](https://github.com/sigstore/cosign/pull/52), but for KMS's that support ed25519 I wonder if we can have an option to support it?

My use case is we use Hashicorp Vault with ed25519 keys to produce signatures for artifacts that are compatible with minisign, I'd like to be able to use cosign with the same keys that already exist to take advantage of our auditing and access control. 

The current implementation of `hashivault` actually allows you to produce a signature from a ed25519 transit key since the API call is the same. However you can't create a public key from an ed25519 transit key since it's not PEM encoded:

```
❯ cosign sign --key hashivault://cosigntest --upload=false --payload=hello.txt ubuntu:latest
Using payload from: hello.txt
vOmbkC7KNLYrr0/hIsis8YrqXp/RuR36Zqsuuyp92l66jIgsCdxJLMxWHxmZjz8SoR0Kx3CWUeOfSCGUWRaQAQ==

❯ cosign public-key --key hashivault://cosigntest
error: PEM decoding failed
```

Getting the `public-key` command to work correctly should be pretty straightforward since Vault returns the keytype so we could encode ed25519 keys differently, but to get verification to work it would also require changing the `verify` command to understand what kind of public key the PEM format is in (ed25519 vs ecdsa). 

What are your thoughts on supporting both key types? Personally I would love to use ed25519 to be more inline with minisign/signify, but understand lack of KMS support and FIPS for ed25519 currently

I have some local work I'd be happy to turn into a PR if we agree on an approach. Thanks!

**Comment by lukehinds** [comment]
Hi @ropnop ,

I think you're change is needed in cosign right? sigstore/sigstore supports multiple key types including ed25519

There is an issue to refactor cosigns keys handling over to here: https://github.com/sigstore/sigstore/issues/81#issuecomment-934410476

Maybe this might make a good opportunity, that way cosign can be modular around key types / curves.

**Comment by dekkagaijin** [comment]
We aren't planning on supporting ed25519 (or really anything other than ECDSA-P256-SHA256) in `cosign sign` unless absolutely necessary. You'd also have to add support in `rekor` and `fulcio`. Simplicity of adopting `cosign`, implementing its spec, and avoiding confusion/downgrade attacks was worth the tradeoff of reduced flexibility. (Pure) ed25519 is relatively difficult to support due to its requirement of unhashed inputs, but it is something that I took into account when designing the `Signer` and `Verifier` interfaces. 

That said, right now we're refactoring `cosign/pkg` to [enable more plugability/composability](https://github.com/sigstore/cosign/issues/844). The end goal is to make it so that the `cosign` cli is only responsible for processing arguments and defining the workflow based on them. This would allow you to more easily substitute ed25519 signers and verifiers in a custom flow, even if you'd have to give up `rekor` and/or `fulcio` features.

**Comment by encodedwitch** [comment]
Hey @lukehinds @dekkagaijin ! - Any updates regarding these questions ^ ? I'm also trying to understand better the whole relationship between Sigstore - Cosign - Fulcio - Minisig - Others to implement these in prod. I think @ropnop made the right questions to help me do it.

**Comment by haydentherapper** [comment]
ed25519 is now supported throughout the sigstore ecosystem.
