### ISSUE TITLE
move tlog pkg functionalities to sigstore

### ISSUE THREAD

**Issue by developer-guy** [sigstore/sigstore#199]
**Description**

There are a bunch of useful functions in cosign's [tlog.go](https://github.com/sigstore/cosign/blob/main/pkg/cosign/tlog.go) file, let's move these all the useful functions over here.

WDYT?

cc: @dentrax @lukehinds

**Comment by lukehinds** [comment]
I am support of it, especially if we can increase the test coverage at the same time and add some integration tests. I am also happy to help out when I can.

Who should I assign as point person? Yourself @developer-guy ?

**Comment by developer-guy** [comment]
that'd be great 🙋🏻‍♂️ yes, please 🙏

**Comment by Dentrax** [comment]
Just thinking, what about moving these function into rekor client instead of sigstore? @lukehinds

**Comment by lukehinds** [comment]
@Dentrax better in here buddy. We moved the fulcio client code into here so it makes sense the rekor client code comes in. It also saves hitting circular dependencies.

**Comment by Dentrax** [comment]
Just noticed that this issue would require adding `github.com/sigstore/rekor` dependency in [go.mod](https://github.com/sigstore/sigstore/blob/main/go.mod), and eventually it will bring lots of _indirect_ dependencies in _sigstore_. Are we still really want to do this? What about implementing these functions into `rekor` instead of `sigstore`?

```
cosign -> sigstore -> rekor client
```

vs.

```
cosign -> rekor client
```

[tlog.go](https://github.com/sigstore/cosign/blob/main/pkg/cosign/tlog.go) contains lots of great functions that can be used in other projects. And sigstore seem like the top level of the dependency triangle.

**Comment by haydentherapper** [comment]
Closing as this will be a part of sigstore-go
