### ISSUE TITLE
Should the checked-in TUF root be V1 or later?

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/sigstore#792]
**Description**

See https://github.com/sigstore/sigstore/blob/main/pkg/tuf/repository/root.json#L142, the V2 TUF root. This root did not have a recorded and publicly documented signing ceremony. Should we switch to the V1 TUF root? It adds one extra network call to GCS when updating the root, but this seems negligible. I think that should be what we form the root of trust from.

@asraa

**Comment by asraa** [comment]
We had actually wanted to embed the latest trust root, not even V2. 

I personally don't think it's necessary since it's still verifiable to load in the root from V1 if you wanted to trust it. But the problem is, earlier roots aren't even TUF compliant. V3 started using TUF compliant expires, so chaining from older roots may not make sense for every client, whereas distributing the latest trusted root in a trusted binary does.

**Comment by asraa** [comment]
i.e. our trust base is the cosign binary. If you don't trust the cosign binary, you're in a much worse situation.

**Comment by haydentherapper** [comment]
That's a good point about the TUF compliance. Thanks!
